### PR TITLE
changes to about page

### PR DESCRIPTION
**Pull request by delsborg**
Changes for a cleaner about page
 removing old features/plan,
 removed old image.
 Open links in new window
Remove table styling and additional table

Deployed to vivo-cub-dev

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Seems good to removed this outdated material. The resulting page feels sparse. I'm wondering, could this be made more useful to the end user? Perhaps Rachel has some ideas? Also, the target Drupal web pages have some broken links and the copy feels dated and not very relevant. Again, perhaps someone with deeper experience in messaging can assist in making this more useful?

**Comment by aviggio** [comment]
Hi Vance -- I agree that we should look at improving this content, and will try to engage Rachel if possible. I also believe that this is a good first step, to remove the outdated/broken link on that About page as well as the outdated/irrelevant "map" image.

**Comment by aviggio** [comment]
Brainstorming: could the next release of the About page test the waters with speaking to specific user types, e.g., faculty looking for collaborators, versus students, versus journalists or others?

**Comment by delsborg** [comment]
Alex, I like that second idea. I also do agree that it's sparse now, but we can't solve all things immediately, so it's a good incremental step. Would be good to place the text items that tend to be static directly into the about page, then for other items that might require more updates into drupal.
Also, things could change in the future as we move towards webcomponents.

**Review by aviggio — APPROVED** [review]
Good first round of changes to clean up About page.

**Pull request merged**
